repos:
  - repo: https://github.com/godaddy/tartufo
    rev: v3.1.3
    hooks:
      - id: tartufo
        name: tartufo
        entry: tartufo
        args: [pre-commit]
        language: python
        language_version: python3.8
        pass_filenames: false