# Deploy DAGs in branch to dev-private as soon as a PR is raised to main
# Please note we have common DAGs and custom DAGs, this deploys custom
# Custom dags are the DAGs that are present in code repository
# Common DAGs are utilities, libs etc present in MWAA instance repo.

name: Branch DAG - Dev-Private

# Run on a PR to main branch only
on:
  pull_request:
    branches:
      - main    
    paths:  # will only deploy dags, there is separate pipeline for code
      - 'dags/**'
      - '**/dags/**'      

# Ensures that only one deploy task will run at a time.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  dev_private_dag:
    uses: gdcorp-dna/de-github-actions-common/.github/workflows/deploy_common.yaml@main  #TODO: Change to commit SHA
    with:
      aws_environment: dev-private
      deployment_type: custom_dag
      branch_to_deploy: ${{ github.head_ref }}      
      runner_group: de-ckpetlbatch-common # for CKPETLBatch account, please use other runner groups if you are not in CKPETL