# Scan secrets on PR, calls common code

name: Scan secrets

# Run on a push to any branch
on:
  push:
    branches:
      - '**'

jobs:
  tartufo_scan:
    uses: gdcorp-dna/de-github-actions-common/.github/workflows/scan_secrets_common.yaml@main  #TODO: Change to commit SHA
    with:
      runner_group: de-ckpetlbatch-common # for CKPETLBatch account, please use other runner groups if you are not in CKPETL
